# Site-wide settings - https://github.com/jekyll/minima/blob/master/_config.yml
# ------------------

title: Jay Agonoy

author:
  name: Jay Agonoy
  email: hello@jayagonoy.com

description: >
  ...and his thoughts on Pop Culture and Life, narrated in pieces


# Build settings
# --------------

remote_theme: jekyll/minima@d4d779a

Minima requires the following plugins:
plugins:
 - jekyll-feed
 - jekyll-seo-tag

 minima:
   skin: dark
   nav_pages:
     - about.md
     - links.md
   show_excerpts: false
   date_format: "%b-%d-%Y"
   hide_site_feed_link: false