baseURL: ""
languageCode: en-US
title: "Jay Agonoy"
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hello There!"
    Content: "I'm Jay, and I've been online since 2006. I write for VTuberNewsDrop.com, and have written for several websites in the past. Welcome to my space, where you can find the stuff I've shared over the years."
  socialIcons:
    - name: facebook
      url: 'https://www.facebook.com/jayagonoycom'
    - name: x
      url: 'https://www.x.com/jayagonoy'
    - name: youtube
      url: 'https://www.youtube.com/@jayagonoy'
    - name: linkedin
      url: 'https://www.linkedin.com/in/jayagonoy'
  cover:
    linkFullImages: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  defaultTheme: dark
  disableThemeToggle: true
  ShowToc: true
  TocOpen: true
  assets:
    favicon: "site/favicon.ico"
    favicon16x16: "site/favicon-16x16.png"
    favicon32x32: "site/favicon-32x32.png"
    apple_touch_icon: "site/apple_touch_icon.png"
    safari_pinned_tab: "site/safari_pinned_tab.svg"
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
  ShareButtons: ["linkedin", "x", "telegram"]

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: about
      name: About
      url: /about
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: search
      name: Search
      icon: search
      url: /search/
      weight: 50
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 40
    
markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
      wrapStandAloneImageWithinParagraph: true

      
outputs:
  home:
    - HTML
    - RSS
    - JSON
    
permalinks:
  posts: "/:slug"

copyright: "&copy; Jay Agonoy. [Terms](/terms) &bull; [Privacy](/privacy)"
  
caches:
  images:
    dir: :cacheDir/images